# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 01:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinestatus',
            name='last_login',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 7, 29, 9, 57, 37, 244343)),
        ),
    ]
