# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 01:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_status', '0002_auto_20170729_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinestatus',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 29, 9, 58, 1, 761395)),
        ),
    ]
