# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 02:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('online_status', '0004_auto_20170729_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinestatus',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
