# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 02:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_status', '0005_auto_20170729_1018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onlinestatus',
            options={'ordering': ['-last_login'], 'verbose_name': 'Online Status', 'verbose_name_plural': 'Online Status'},
        ),
    ]
